name: CI Pipeline

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.py"
      - "**.build"
      - "**.m"
      - "**.mm"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.py"
      - "**.build"
      - "**.m"
      - "**.mm"

jobs:
  meson_build:
    name: Running on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-2022]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Meson and Ninja
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Generate build file
        run: python meson-generator.py
      - name: Configure
        run: meson setup builddir -Dwith_test=enabled
      - name: Compile
        run: meson compile -C builddir

  cmake_build:
    name: Running on ${{ matrix.os }} with CMake
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.21'
      - name: Configure CMake
        run: cmake -B build
      - name: Build with CMake
        run: cmake --build build
