name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.py"
      - "**.cpp"
      - "**.pyx"
      - "**.build"

permissions:
  contents: read

jobs:
  meson_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meson_version: ["1.0.0", "1.1.0", "1.2.0", "1.3.0", "latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
        if [[ "${{ matrix.meson_version }}" == "latest" ]]; then
          pip install meson ninja
        else
          pip install "meson==${{ matrix.meson_version }}" "ninja==1.11.1"
        fi
        sudo apt-get install -y gcc
    - name: Generate Build Files
      run: |
        python meson-generator.py
    - name: Setup Build Directory
      run: |
        meson setup builddir
    - name: Compile Source Code
      run: |
        meson compile -C builddir

  host_macosx:
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]  # macOS versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Generate Build Files
      run: |
        python meson-generator.py
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir

  host_windows:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
        mingw: [false, 'mingw32', 'mingw64', 'MSYS']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup MinGW/MSYS
      if: matrix.mingw != false
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw }}
        update: true
    - name: Generate Build Files
      run: |
        python meson-generator.py
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir

  host_ubuntu:
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
          sudo apt-get install -y gcc
    - name: Generate Build Files
      run: |
        python meson-generator.py
    - name: Setup Build Directory
      run: |
          meson setup builddir
    - name: Compile Source Code
      run: |
          meson compile -C builddir
